export const demoTexts = [
    `Welcome to Presto Reader. Right now, you are reading these words one at a time. This is called RSVP, Rapid Serial Visual Presentation, and it is about to change how you read.

Most people read at about 200 to 250 words per minute. That is roughly the speed of speech. But here is the thing: your brain can process language much faster than that. The bottleneck is not comprehension. It is your eyes.

When you read a book or article, your eyes do not glide smoothly across the line. They jump in quick movements called saccades, landing on each word, then leaping to the next. These tiny jumps take time. In fact, eye movement accounts for most of your reading time, not understanding.

RSVP eliminates this entirely. The words come to you. Your eyes stay still. You simply receive.

Notice the red letter in each word. That is the Optimal Recognition Point, the spot where your eye naturally wants to land. Research shows that each word has an ideal fixation point, usually slightly left of center. By highlighting it, we reduce the cognitive effort of finding where to look. Just let your gaze rest on that red letter and allow the words to flow past.

Now, let us talk about the voice in your head. You are probably hearing these words as you read them. That inner narration is called subvocalization, and it is the single biggest limit on your reading speed. Your inner voice maxes out around 150 to 200 words per minute. As long as you are sounding out every word internally, you cannot read faster than you can speak.

Here is the secret: you do not need to silence that voice by force. You simply need to outpace it. As the speed increases, your inner voice will not be able to keep up. Let it fall away. You will shift from hearing the words to simply knowing them. Meaning will arrive directly, without the detour through sound.

The speed is increasing now. You may have noticed. This is training mode. Do not fight it. Relax your face. Relax your eyes. Breathe. Your brain is adapting.

If you feel like you are missing words, that is normal. Your conscious mind thinks it needs every word, but your brain is filling in gaps constantly. You do this in conversation all the time. Trust the process.

Comprehension at high speeds is different from slow reading. You will not remember exact phrasing. But you will retain the meaning, the structure, the key ideas. Studies show that retention of core concepts remains strong even at double or triple normal reading speeds. What changes is the texture of the experience.

The speed is still climbing. Stay with it. Do not chase the words. Let them come to you. Keep your gaze soft, centered on that red focus point. You are not reading anymore. You are absorbing.

This is the flow state. Thoughts quiet. The outside world fades. There is only the stream of meaning entering your mind. Elite readers describe it as watching a movie made of ideas. You are not decoding symbols. You are receiving understanding directly.

With practice, you will find your edge: the fastest speed at which comprehension holds. That edge will move. What feels impossibly fast today will feel comfortable in a week. Your brain is plastic. It adapts. The more you train, the faster you can go while retaining meaning.

You are still here. The speed is high now. And yet you understand. This is what your brain is capable of. This is what reading can become.

Welcome to faster reading.`,
    `A huge black bear that made its den in the crawl space under a Los Angeles area man's house for more than a month has finally been evicted. Altadena resident Ken Johnson said the animal began denning beneath his home around Thanksgiving, twisting gas lines and toppling bricks as he came and went. Surveillance video showed the bear easily tearing away screening and other obstacles and squeezing through a small opening. Johnson said in a phone interview Friday that he first asked state wildlife officials for help, but the air horns and paintball guns they deployed didn't work. So he turned to BEAR League, a California-based nonprofit that bills itself as specializing in "living in harmony with bears." The bear was out within about 20 minutes after members from the group arrived, Johnson said. In a social media post on Thursday, the group said that one of its most experienced responders crawled beneath the home and got behind the bear — which it estimated weighs more than 500 pounds (227 kilograms) — to encourage the animal to leave. "There's the relief — it feels like, you know, you had a bunch of dinner guests over and now the party's over — well it wasn't a party — but you know they're gone and now you've got a bunch of dirty dishes and empty glasses to deal with," Johnson said. The group placed an "unwelcome" mat, which delivers an electric shock, at the opening. Video footage showed the bear returning to the house, stepping on the mat and then running away. Dave Fleishman, a BEAR League spokesperson who helped evict the animal, said it was one of the largest black bears he has seen. "He's in my top three," Fleishman said. "He's an old soul ... I think he just wanted a quiet place for the winter," he added. "But he'd done a tremendous amount of damage to Ken's house. And so, you don't want Ken's house to burn down or the rest of Altadena to burn down because of a ruptured gas line." Fleishman said the team was able to move the bear quickly because the house has two crawl spaces, making access easier. He called it a "standard eviction" the group regularly handles, particularly in the Lake Tahoe area. Johnson described having the bear around as "unsettling." Since the eviction, the bear came back at least once before moving on, he said. "It's just the constant tension of if he if he decides to come out I have to be ready," he said. Johnson said the animal caused thousands of dollars in damage, which has been particularly tough to deal with because he lost his job after last year's Eaton wildfire. The bear shredded ductwork under the house and twisted natural gas piping, Johnson said. He's set up a GoFundMe page seeking to repair the damage and make his house livable again.`,
    `It was the hunter's first time outside Montana. He woke, stricken still with the hours-old vision of ascending through rose-lit cumulus, of houses and barns like specks deep in the snowed-in valleys, all the scrolling country below looking December—brown and black hills streaked with snow, flashes of iced-over lakes, the long braids of a river gleaming at the bottom of a canyon. Above the wing the sky had deepened to a blue so pure he knew it would bring tears to his eyes if he looked long enough. Now it was dark. The airplane descended over Chicago, its galaxy of electric lights, the vast neighborhoods coming clearer as the plane glided toward the airport—streetlights, headlights, stacks of buildings, ice rinks, a truck turning at a stoplight, scraps of snow atop a warehouse and winking antennae on faraway hills, finally the long converging parallels of blue runway lights, and they were down. He walked into the airport, past the banks of monitors. Already he felt as if he'd lost something, some beautiful perspective, some lovely dream fallen away. He had come to Chicago to see his wife, whom he had not seen in twenty years. She was there to perform her magic for a higher-up at the state university. Even universities, apparently, were interested in what she could do. Outside the terminal the sky was thick and gray and hurried by wind. Snow was coming. A woman from the university met him and escorted him to her Jeep. He kept his gaze out the window. They were in the car for forty-five minutes, passing first the tall, lighted architecture of downtown, then naked suburban oaks, heaps of ploughed snow, gas stations, power towers, and telephone wires. The woman said, "So you regularly attend your wife's performances?" "No," he said. "Never before." She parked in the driveway of an elaborate modern mansion, with square balconies suspended over two garages, huge triangular windows in the façade, sleek columns, domed lights, a steep shale roof. Inside the front door about thirty nametags were laid out on a table. His wife was not there yet. No one, apparently, was there yet. He found his tag and pinned it to his sweater. A silent girl in a tuxedo appeared and disappeared with his coat. The granite foyer was backed with a grand staircase, which spread wide at the bottom and tapered at the top. A woman came down. She stopped four or five steps from the bottom and said, "Hello, Anne" to the woman who had driven him there and "You must be Mr. Dumas" to him. He took her hand, a pale, bony thing, weightless, like a featherless bird. Her husband, the university's chancellor, was just knotting his bow tie, she said, and she laughed sadly to herself, as if bow ties were something she disapproved of. The hunter moved to a window, shifted aside the curtain, and peered out.`,
];
